name: Create Production Builds
on:
  push:
    branches: ['main']
jobs:
  build_android:
    type: build
    name: Build Android (production)
    params:
      platform: android
      profile: production
      message: "Android production build triggered"
